export const APPCONSTANTS = {
    APP_TITLE: "CINEFLEX",
    HOME: "HOME",
    ALL_MOVIES: "All Movies",
    LOGIN: "Login",
    LIKES: "Likes",
    ACTORS: "Actors",
    LOAD_MORE: "LOAD MORE",
    LOGOUT: "Logout",
    NOW_SHOWING: "Now Showing",
    SINDEL_IMAGE: "SINDEL IMAGE",
    MOBILE_NUMBER_PRIZE: "Your Mobile Number can win you exciting prizes",
    MOBILE_NUMBER_PLACEHOLDER: "Enter Mobile Number",
    FEELING_LUCKY: "I'm Feeling Lucky",
    MOBILE_MAX_LENGTH: 10,
    NIL: "NIL",
    RESUMES: "Resumes in ",
    ERROR_OCCURED: "Error occured",
    LOTTORY_WON: "Hurray! You won a free ticket to Blind Date on Wednesday ",
    DEFAULT_INPUT_TYPE: "text",
    LOTTERY_ERROR_MESSAGE: "Sorry :( Better Luck Next Time",
    TRAILERS: "Trailers",
    NEED_TO_SIGN_IN: "You need to sign in to view Trailers",
    SIGN_IN: " Sign In Now",
    WATCH_NOW: "WATCH NOW",
    TRAILER_DESCRIPTION: "Sintel tells the story of a friendship between a girl named Sintel, a baby dragon and the desperate lengths she will go to when that friendship is taken from her. Sintel is created by Blender in 2010 as a pet project to demonstrate Blender capabilities.",
    TRAILER_TITLE: "Sintel",
    SHORT_TEASERS: "Short Teasers",
    OTHER_LANGUAGES: "View in Other Languages",
    LANGUAGES: ["E","தா","మ","ഹം"],
    ADVERTISEMENT: "Advertisement in ",
    VIDEO_RESUMES: "Video Resumes in ",
    LOGIN_INFO: "Logging into CineFLEX will give you access to full videos and movies. You can sit back, relax and watch at your home",
    EMAIL: "Email",
    PASSWORD: "Password",
    NOW_SHOWING_MOVIE_DETAILS: {
        NAME: "Sintel",
        SRC: "https://www.youtube.com/embed/CaimKeDcudo",
        DESCRIPTION: "Sintel tells the story of a friendship between a girl named Sintel, a baby dragon and the desperate lengths she will go to when that friendship is taken from her. Sintel is created by Blender in 2010 as a pet project to demonstrate Blender capabilities.",
    }
}