
export const appConstants={
    menuMen:"MEN",
    menuWomen:"WOMEN",
    menuKids:"KIDS",
    menuAbout:"ABOUT US",
    avatarName:"Hi Ashok",
    wishlist:"WISHLIST",
    addToBag:"ADD TO BAG",
    myCart:"MY CART",
    placeOrder:"PLACE ORDER",
    smallSize:"S",
    mediumSize:"M",
    largeSize:"L",
    shopNow:"SHOP NOW",
    remove:"REMOVE",
    continueShopping:"CONTINUE SHOPPING",
    orderPlaced:"Order Placed",
    successfullOrder:"Your Order has been successfully placed.",
    thankYou:"Thank you for shopping with us.",
    orderTrack:"You can track you orders online through the Invoice Number",
    emptyCart:"No items are available in your cart to place the order !!!",
}
