export const AppConstants = {
    MOCK_USERS: [{
        name:"laxis",
        password:"password"
    }, {
        name:"laxman",
        password:"password"
    }, {
        name:"durga",
        password:"password"
    }],
    HI: "Hi",
    SESSIONTIME: "SESSION TIME",
    MIN: "MIN",
    SEARCH_HEADING: "Travelling first leaves you speechless, then turns you into a story teller",
    SEARCH_SUBHEADING_ONE: "Take every chance you get in your life, because something will happen only once. Once in a while, go somewhere you have never been before.",
    SEARCH_SUBHEADING_TWO: "With TripZone, you could book amazing holiday spots with low fares. We understand how travelling can impact your budget.",
    SEARCH_PLACEHOLDER: "Type your favorite destination here!",
    PLAN_MY_TRIP: "PLAN MY TRIP",
    SOURCE: "Source",
    DESTINATION: "Destination",
    SEARCH: "SEARCH",
    GLOBAL_PROMOTION_TITLE: "The World is Beautiful. Keep Travelling",
    TRAVELLING_TO: "Travelling to ",
    KNOW_MORE: "Know more about it.",
    NO_CITIES: "We don’t currently service this city.",
    PREVIOUS: "PREVIOUS",
    BOOK: "BOOK",
    AVAILABLE_FLIGHTS: "AVAILABLE FLIGHTS",
    NO_FLIGHTS_AVAILABLE: "No Flights Found",
    BOOK_NOW: "BOOK NOW",
    MEMBERSHIP_DISCOUNT: "Membership Discount",
    TAX_AMOUNT: "Tax Amount",
    MEMBERSHIP_RENEWAL: "You can further increase your membership discount by renewing your membership. Choose Number of Years to Renew",
    COVID_DONATION: "You can donate to COVID-19 Care Fund by increasing the Tax Component. Choose % of Tax Component to be increased.",
    TICKET_SENDING_DETAILS: "Your Ticket will be emailed to your registered email and phone number.",
    PROCEED_TO_PAY: "PROCEED TO PAY",
    YEAR: "YEAR",
    NIL: "NIL",
    DOLLAR: "$",
    IMAGE_NOT_FOUND: "https://www.thermaxglobal.com/wp-content/uploads/2020/05/image-not-found-300x169.jpg",
    SELECTED: "selected",
    SEARCHED: "searched",
    NO_PREVIOUS_DESTINATION: "No previous destination",
}