export const AppConstants = {
    ShopName:"SITBACK",
    Couches:"COUCHES",
    Chairs:"CHAIRS",
    Dining:"DINING",
    UserName:"Laxman",
    YourHomeWithLove:"Your Home, With Love",
    ComeChoose:"Come, Choose from millions of products",
    ShopNow:"SHOP NOW",
    CopyRights:"COPYRIGHTS 2020",
    Year:"YEAR",
    Years:"YEARS",
    Guarantee:"GUARANTEE",
    AddToWishlist:"ADD TO WISHLIST",
    AddToCart:"ADD TO CART",
    MyCart:"MY CART",
    MyWishlist:"MY WISHLIST",
    Add:"+",
    Delete:"-",
    PlaceOrder:"PLACE ORDER",
    TotalAmount:"TOTAL AMOUNT",
    WishlistToCart:"WISHLISTTOCART",
    FakeDescription:"Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s.",
    Nil:"NIL",
    OrderConfirmation:"Order Confirmation",
    ThankYouForShopping:"Thank you for shopping with us. the items will be delivered within 7 days.",
    Quantity:"Quantity"
}